# Generated by Django 4.0.6 on 2022-07-27 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, max_length=255, null=True)),
                ('programming_language', models.CharField(blank=True, max_length=255, null=True)),
                ('source_code', models.URLField(blank=True, max_length=255, null=True)),
                ('demo_link', models.URLField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'projects',
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Projectree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectree_name', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('favicon', models.URLField(blank=True, null=True)),
                ('theme', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('project_items', models.ManyToManyField(blank=True, related_name='projects', to='projectrees.projectitem')),
                ('user', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'projectrees',
                'db_table': 'projectree',
            },
        ),
        migrations.AddIndex(
            model_name='projectree',
            index=models.Index(fields=['user', 'created_at'], name='projectree_user_id_7c85e1_idx'),
        ),
        migrations.AddIndex(
            model_name='projectitem',
            index=models.Index(fields=['name', 'created_at'], name='projects_name_989241_idx'),
        ),
    ]
