# Generated by Django 4.0.6 on 2022-07-28 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectrees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectree',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='PublishedProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('projectree', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projectrees.projectree')),
                ('user', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'published projects',
                'db_table': 'published_projects',
            },
        ),
        migrations.AddIndex(
            model_name='publishedprojects',
            index=models.Index(fields=['name', 'projectree', 'user', 'created_at'], name='published_p_name_228444_idx'),
        ),
    ]
